ONSdigital/rdsa-utils

.github/workflows/deploy_mkdocs.yaml, CHANGELOG.md
Fix bug in `deploy_mkdocs.yaml`, fix Python version to `3.11` not the latest Python version.
<br> …
=> Bug Fix: mkdocs Deploy

.github/workflows/deploy_mkdocs.yaml, CHANGELOG.md
Fix bug in `deploy_mkdocs.yaml`, fix Python version to `3.10` not Python version `3.11`.
<br> …
=> Fix Python Version to 3.10 in deploy_mkdocs.yaml

.github/workflows/deploy_mkdocs.yaml, CHANGELOG.md
Fix bug in `deploy_mkdocs.yaml`, fix Python version to `3.10` not Python version `3.11`.
<br> …
=> Bug Fix deploy_mkdocs.yaml -- missing quotes for Python version

CHANGELOG.md, mkdocs.yml, setup.py
Closes #37 
Added more `mkdocs` Plugins:
-  `mkdocs-git-revision-date-localized-plugin`
-  `mkdocs-jupyter`
More user-friendly navigation on `mkdocs` by adding these lines of code in `mkdocs.yml`:
```
features:
- navigation.tabs
- navigation.tabs.sticky
- navigation.indexes
```
Upgrade `mkdocs-tech-docs-template` version to `0.1.2`.
<br>
- **Test coverage**: Unit tests …
=> mkdocs Extensions & Upgrades

CHANGELOG.md, rdsa_utils/cdsw/io/output.py, tests/cdsw/io/test_cdsw_output.py
Add `save_csv_to_hdfs` function to `cdsw/io/output.py`.
- Implemented the `save_csv_to_hdfs` function, which facilitates saving DataFrames as CSV files to HDFS with optional coalescing.
- Due to the complexity of mocking **HDFS** interactions, tests for this function have been marked as **skipped**.
The module encapsulates functionality for output operations within the CDSW Platform.
<br>
- **Complexity**: The code is not overly complex, logic has been split into appropriately sized …
=> CDSW CSV Writer Function

CHANGELOG.md, setup.py
pytest `v8.0.0` now fails with `pytest-lazy-fixture`.
**Fix:** Pin `pytest` version in `setup.py` due to: https://github.com/TvoroG/pytest-lazy-fixture/issues/65
<br>
Suggestions should be tailored to the code that you are …
=> Bug Fix: pytest-lazy-fixture fails with pytest version 8.0.0

CHANGELOG.md, README.md
Enhanced `README.md` headers with relevant emojis for improved readability and engagement.
<br> …
=> Update README.md with Emojis

CHANGELOG.md
**Changes:**
- Added note on missing pre-`v0.1.8` releases due to `deploy_pypi.yaml` issues.
- Included GitHub and PyPI links for `v0.1.8`.
<br>
<br>
Suggestions should be tailored to the code that you are reviewing. …
=> Update CHANGELOG for Release Link Clarity

CHANGELOG.md, rdsa_utils/cdsw/helpers/hdfs_utils.py, rdsa_utils/cdsw/io/output.py, tests/cdsw/helpers/test_hdfs_utils.py, tests/cdsw/io/test_cdsw_output.py
- Refactor `save_csv_to_hdfs` to use functions in `/cdsw/helpers/hdfs_utils.py`.
- Add function `delete_path` in `/cdsw/helpers/hdfs_utils.py`, and refactor docstring for `delete_file` and `delete_dir`. 
<br>
Suggestions …
=> Refactor Function: save_csv_to_hdfs

.pre-commit-config.yaml, CHANGELOG.md
- Added `gitleaks` and local `restrict-filenames` hooks to `.pre-commit-config.yaml` to prevent adding secrets and data files to `rdsa-utils` repo.
Closes #68 
<br>
Suggestions should be tailored to the code that you are …
=> Improve Pre-Commit Hooks: Prevent Secrets Leak and Prevent Data Files

CHANGELOG.md, docs/branch_and_deploy_guide.md
Updated the `branch_and_deploy_guide.md` document by adding a new section titled **"Merging Development to Main: A Guide for Maintainers"**. This addition offers detailed steps and best practices for maintainers during the crucial phase of merging changes from the `development` branch to the `main` branch, ensuring a seamless and efficient release process.
<br>
- **Test …
=> Modified branch_and_deployment.md: Add Maintainer's Guide Section

CHANGELOG.md, README.md
- Updated `README.md` to include new badges for Deployment Status and PyPI version.
Be critical and clear, but not mean. Ask questions and …
=> Add GitHub Workflow Badges to README.md

CHANGELOG.md, docs/branch_and_deploy_guide.md
Added section on synchronising the `development` branch with `main` to the `branch_and_deploy_guide.md` file.  
<br>
Be critical and …
=> Update branch_and_deploy_guide.md; Add Section -- Sync Development Branch to Main Branch

CHANGELOG.md, docs/contribution_guide.md
Updated `contribution_guide.md`; fix code block rendering issue in `mkdocs` by  removing extra whitespaces.
<br>
Be critical and clear, …
=> Update contribution_guide.md: Fix mkdocs Rendering Issue

CHANGELOG.md, README.md
Added a new section titled **"Further Reading on Reproducible Analytical Pipelines"**  to the `README.md`. 
This section provides links and descriptions to resources that are essential for understanding and implementing RAP best practices, including version control, modular coding, unit testing, and peer review.
<br>
- **Test coverage**: Unit tests cover essential …
=> Add Further Reading Section on RAP to README.md

CHANGELOG.md, README.md
Revised the "Further Reading on Reproducible Analytical Pipelines" section in the `README.md` for clarity.
<br>
Be critical and clear, but …
=> Update Further Reading on RAPs

CHANGELOG.md, README.md
Updated `README.md` added Ruff and Python versions badges.
<br> …
=> Add More Badges to README.md

.github/workflows/pull_request_workflow.yaml, CHANGELOG.md, docs/reference.md, rdsa_utils/cdp/helpers/s3_utils.py, rdsa_utils/exceptions.py, setup.cfg, tests/cdp/helpers/test_s3_utils.py
This merge request introduces the `s3_utils.py` module within the `cdp/helpers` directory. 
The new module includes a suite of functions designed to enhance interactions with AWS S3, such as uploading, downloading, copying, and deleting files, as well as creating folders.
<br>
- **Test coverage**: Unit tests cover essential functions for a reasonable range of inputs and …
=> Add new `s3_utils.py` module to `cdp/helpers`

CHANGELOG.md, rdsa_utils/cdp/helpers/s3_utils.py, tests/cdp/helpers/test_s3_utils.py
Add "Examples" section in `delete_folder()` docstring in `s3_utils.py`.
<br>
Be critical and clear, but not mean. Ask questions and set …
=> Add Examples section in delete_folder() docstring in s3_utils.py

CHANGELOG.md, rdsa_utils/cdp/io/output.py, tests/cdp/io/test_cdsw_output.py
Added `save_csv_to_s3` function in `cdp/io/output.py`.
<br> …
=> Add save_csv_to_s3() function in cdp/io/output.py

CHANGELOG.md, rdsa_utils/cdp/helpers/s3_utils.py
This merge request addresses the inconsistent parameter naming across the S3 utility functions in `s3_utils.py`. The following changes have been made:
- Unified `key` and `s3_object_name` to `object_name`.
- Generalized `local_file_path` and `local_folder_path` to `local_path`.
- Clarified `source_bucket`/`dest_bucket` and `source_key`/`dest_key` to `source_bucket_name`, `source_object_name`, `destination_bucket_name`, and `destination_object_name`.
- Standardised `folder_name` to `folder_path` for all folder-related parameters.
These changes enhance code readability, maintainability, and ensure consistent usage of parameter names across all utility functions.
<br>
- **Style …
=> Standardise Parameter Names for Consistency in S3 Utility Functions

CHANGELOG.md, rdsa_utils/io/output.py, tests/io/test_output.py
Added `zip_folder` function to `io/output.py`.
<br> …
=> Added zip_folder() function to io/output.py

CHANGELOG.md, rdsa_utils/helpers/pyspark.py, tests/helpers/test_pyspark.py
Add `load_csv`  to `helpers/pyspark.py`.
<br>
<details><summary>These …
=> Feature: PySpark load_csv()

CHANGELOG.md, rdsa_utils/cdp/io/input.py, tests/cdp/io/test_cdsw_input.py
Added `get_tables_in_database` to `cdp/io/input.py`.
<br> …
=> Feature: Add function get_tables_in_database()

CHANGELOG.md, rdsa_utils/cdp/io/input.py, rdsa_utils/helpers/pyspark.py, tests/cdp/io/test_cdsw_input.py
Added more parameters to `load_and_validate_table()` in `cdp/io/input.py`.
<br>
Be critical and clear, but not mean. Ask questions and set …
=> Feature: Add more parameters to load_and_validate_table()

.github/workflows/deploy_mkdocs.yaml, .github/workflows/pull_request_workflow.yaml, CHANGELOG.md, mkdocs.yml, setup.cfg
Update mkdocs theme to [ons-mkdocs-theme](https://github.com/ONSdigital/ons_mkdocs_theme)
<br> …
=> Docs: Update to ons-mkdocs-theme

CHANGELOG.md, rdsa_utils/cdp/helpers/s3_utils.py, tests/cdp/helpers/test_s3_utils.py
Added `load_csv` to `cdp/helpers/s3_utils.py`. This loads a CSV from S3 bucket into a Pandas DataFrame.
<br>
Be critical and clear, but …
=> Feature: load_csv() -- Reads CSV from S3 Bucket into Pandas DataFrame

CHANGELOG.md, rdsa_utils/helpers/pyspark.py, tests/helpers/test_pyspark.py
Add kwargs Parameter to `load_csv()`
<br>
<details><summary>These …
=> Add kwargs Parameter to load_csv()

CHANGELOG.md, rdsa_utils/cdp/helpers/s3_utils.py, rdsa_utils/cdp/io/output.py, rdsa_utils/exceptions.py, tests/cdp/helpers/test_s3_utils.py
- Added `InvalidS3FilePathError` to `exceptions.py`.
- Added `validate_s3_file_path` to `s3_utils.py`.
- Call `validate_bucket_name` and `validate_s3_file_path` function inside `cdp/helpers/s3_utils/load_csv`.
<br> …
=> Feature: More validation for save_csv_to_s3() and load_csv()

CHANGELOG.md, rdsa_utils/helpers/pyspark.py, tests/helpers/test_pyspark.py
Improved `truncate_external_hive_table` to handle both partitioned and non-partitioned Hive tables, with enhanced error handling and support  for table identifiers in `<database>.<table>` or `<table>` formats.
*You can delete options that are not relevant.*
<br>
- **Test coverage**: Unit tests cover essential functions for a reasonable range of inputs and conditions. …
=> Fix truncate_external_hive_table()

CHANGELOG.md, README.md
Added "How the Project is Organised" section to `README.md`.
<br> …
=> Added "How the Project is Organised" section to README.md

CHANGELOG.md, rdsa_utils/helpers/pyspark.py
This change will ensure compatibility with newer version of PySpark to fix the UserWarning: `UserWarning: DataFrame.sql_ctx is an internal property, and will be removed in future releases. Use DataFrame.sparkSession instead`.
<br>
- **Test coverage**: Unit tests cover essential functions for a reasonable range of inputs and conditions. Added and existing tests pass on my …
=> Bug Fix: Changes to cut_lineage() for UserWarning

CHANGELOG.md, rdsa_utils/cdp/io/output.py, tests/cdp/io/test_cdsw_output.py
Modified `insert_df_to_hive_table` function in `cdp/io/output.py`. Added support for creating non-existent Hive tables, repartitioning by column or partition count, and handling missing columns with explicit type casting.
*You can delete options that are not relevant.*
<br>
- **Test coverage**: Unit tests cover essential functions for a reasonable range of inputs and …
=> Improvement: Add features to insert_df_to_hive_table()

CHANGELOG.md, rdsa_utils/cdp/helpers/s3_utils.py, tests/cdp/helpers/test_s3_utils.py
This PR introduces pagination support when listing files from S3 buckets, as in many cases there are well over 1000 (the limit for a single `list_objects_v2` call).  Change summary:
- Modifies the `list_files` function to use pagination via boto3's get_paginator, replacing direct client.list_objects_v2 call with paginator.paginate
- Iterates through paginated results to collect all files
This is an enhancement that improves performance w/o breaking existing functionality, tested on the existing test suite for this module using pytest.
<br>
- **Functionality**: The code works as expected, handles …
=> Improvement: multi page s3 list files

.pre-commit-config.yaml, .ruff.toml, CHANGELOG.md, rdsa_utils/test_utils.py, tests/cdp/helpers/test_hdfs_utils.py, tests/cdp/helpers/test_s3_utils.py, tests/cdp/io/test_cdsw_input.py, tests/cdp/io/test_cdsw_output.py, tests/gcp/helpers/test_gcp_utils.py, tests/helpers/test_pyspark.py, tests/helpers/test_python.py, tests/io/conftest.py, tests/methods/test_averaging_methods.py, tests/test_logging.py
- Ran `ruff check . fix` on the codebase to comply with new PEP rules.
- Added rules to `ruff.toml` to ignore A005 warnings for `rdsa_utils/logging.py` and `rdsa_utils/typing.py`.
- Upgraded `black`, `ruff`, `gitleaks` to the latest version  in `.pre-commit-config.yaml`.
<br>
- **Test coverage**: Unit tests cover essential functions for a reasonable range of inputs and …
=> Run ruff on codebase to comply with new PEP rules

.github/workflows/pull_request_workflow.yaml, CHANGELOG.md, LICENSE, docs/contribution_guide.md, setup.cfg
This Pull Request introduces rdsa-utils compatibility with recent Python versions.
I have used the same approach that I have used on other projects.
Still need to check the unit tests are run on both new versions of Python
=> Improvement: Update Setup for Python 3.12 and 3.13

CHANGELOG.md, README.md
Added acknowledgements to colleagues from DSC and MQD in `README.md`
=> Update README: Add section for Acknowledgements

CHANGELOG.md, rdsa_utils/cdp/helpers/s3_utils.py, setup.cfg, tests/cdp/helpers/test_s3_utils.py, tests/helpers/test_pyspark.py
- Added `write_excel` function to `cdp/helpers/io/s3_utils.py`.
- Added `xlsxwriter` and `openpyxl` dependency due to `write_excel` function 
in `cdp/helpers/io/s3_utils.py`
<br>
Suggestions should be tailored to the code …
=> Feature: write_excel() in cdp/helpers/io/s3_utils.py

.ruff.toml, CHANGELOG.md
Added `__init__.py` to `helpers/pyspark_log_parser`.
=> Module Fix -- PySpark Log Parser

CHANGELOG.md, setup.cfg
- Added `include_package_data = True` and `* = *.db` to `setup.cfg` to include SQLite database files in the package.
=> DB Fix -- PySpark Log Parser

CHANGELOG.md, docs/contribution_guide.md
- Add house-style example functions and unit tests to `docs/contribution_guide.md`.
<br> …
=> Improve Docs: Better Contribution Guide

CHANGELOG.md, rdsa_utils/cdp/helpers/s3_utils.py, tests/cdp/helpers/test_s3_utils.py
- Added `zip_local_directory_to_s3` & `zip_s3_directory_to_s3` to `cdp/helpers/s3_utils.py`.
<br> …
=> Feature: Zip S3 Functions

.github/workflows/generate_coverage_badge.yaml, CHANGELOG.md, README.md
- Added `generate_coverage_badge.yaml` GitHub Action to generate pytest coverage report when pushing to the `main` branch.
- Updated `README.md` to include information about pytest coverage badge.
<br>
Suggestions should …
=> Generate README Coverage Badge

CHANGELOG.md, rdsa_utils/helpers/pyspark.py, tests/helpers/test_pyspark.py
Added `smart_coalesce` function in `helpers/pyspark.py`.
<br> …
=> Feature: smart_coalesce()

CHANGELOG.md, rdsa_utils/logging.py, tests/test_logging.py
Added support in `init_logger_advanced` to detect existing root logger handlers and prevent duplicate configuration; updated corresponding unit tests.
<br>
Suggestions should be tailored to the code that you are reviewing. …
=> Modify init_logger_advanced()

CHANGELOG.md, rdsa_utils/helpers/pyspark.py, tests/helpers/test_pyspark.py
Added function `filter_out_values` to `helpers/pyspark.py`.
<br> …
=> Add function: filter_out_values()

CHANGELOG.md, rdsa_utils/cdp/io/output.py, tests/cdp/io/test_cdsw_output.py
Updated `insert_df_to_hive_table` function in `cdp/io/output.py`; enhanced schema mismatch error logging to show specific column differences.
<br>
Suggestions should be tailored to the code that you are reviewing. Provide …
=> Improve: insert_df_to_hive_table() -- better schema mismatch logger

CHANGELOG.md, rdsa_utils/helpers/pyspark.py, tests/helpers/test_pyspark.py
Added functions `check_year_range` & `assert_same_distinct_value` to `helpers/pyspark.py`.
*You can delete options that are not relevant.*
<br>
Suggestions should be tailored to the code that you are reviewing. Provide …
=> Add PySpark Functions: check_year_range & assert_same_distinct_values

CHANGELOG.md, rdsa_utils/helpers/pyspark.py
Reordered docstrings to place Returns above Raises in `check_year_range` in `helpers/pyspark.py`
<br>
Be critical and clear, but not mean. …
=> Rearrange Docstring: check_year_range

CHANGELOG.md, rdsa_utils/cdp/helpers/s3_utils.py, rdsa_utils/helpers/python.py, tests/cdp/helpers/test_s3_utils.py, tests/helpers/test_python.py
- Added `sha256_sum`, `parse_pyproject_metadata`, `validate_env_vars` to `helpers/python.py`.
- Added `create_s3_uri` & `split_s3_uri` to `cdp/helpers/s3_utils.py`.
<br>
Suggestions should be tailored to the code that you …
=> Feature: More Python & S3 Utility Functions
